### PR TITLE
Insert a test package for mp1

### PR DESCRIPTION
**Pull request by jranalli**
Create a test package requiring pytest. You can use this to determine whether you've fixed the bugs in mp1. It has about 70% coverage, but that could be improved by writing more tests.

### CODE REVIEW

**Comment by jranalli** [comment]
FYI it's actually possible, if you implement testing this way, to have Github run the tests all the time to make sure that your code (and especially code that others wish to contribute) is continually passing the tests. See here: https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/#what-are-github-actions

**Comment by jranalli** [comment]
Just a point to consider as to streamlining. The philosophical purpose of testing is to put a box around what the code does, so that you know if something you changed broke one of the outputs. For example, the reimplementation of d_s led to a failure in the supercritical cases, but not subcritical. As such, my understanding is that the idea is to very explicitly test one piece of functionality per test function, rather than trying to figure out efficient ways to write the tests. The testing output (in this case pytest, but others are similar) is actually harder to interpret when you have multiple asserts within a single function. So arguably, you could even say that what I wrote is already too condensed.

Your code has kind of two separate testing needs, and I don't know if they ought to be separated (I just put them together in one thing here). The more fundamental software thing is testing that the methods behave, even with variable input types, because that's how I identified a couple of these bugs. The other is the scientific validity relative to the NIST reference.

**Comment by chmarti1** [comment]
I'm pretty familiar with the philosophy of testing.  I've had three incarnations of the _test() method that take the data through a series of "truth" values.  The new versions are not yet finished (except on the ig class, which has embedded "truth" values in the data set), so version 2.1.0 was pushed with point-by-point validation against source data and 1000-element random value array generation at the command line.  Still, as you're pointing out, the new version has had bugs.

Let's take this conversation offline from the Github repository.
-
Chris
________________________________

**Comment by jranalli** [comment]
Adjusting this by adding a separate branch with tests.

**Pull request closed without merging**
